"""Blueprint defaults from probe value histograms (bpstat lines): run once on the original
(engine adds its defaults) and once on moho64 with --raw-blueprints (script tables only).
For every field the original has on more blueprints than the scripts define, the added
values are (original histogram - script histogram); a field whose added values are all one
value has that value as its default.
usage: gen_bp_defaults.py raw.log orig.log > src/sim/bp_defaults.inc"""
import re, sys, collections
def load(path):
    st = {}
    for l in open(path, encoding='latin1'):
        l = l.rstrip('\r\n')
        if not l.startswith('info: PROBE bpstat '): continue
        rest = l[len('info: PROBE bpstat '):]
        m = re.match(r'(\S+) (\d+) distinct=(\d+) ?(.*)$', rest)
        if not m: continue
        p, n, nd, vals = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4)
        h = {}
        for part in vals.split(' | ') if vals else []:
            v, _, c = part.rpartition(' x')
            h[v] = int(c)
        st[p] = (n, nd, h)
    return st
raw, orig = load(sys.argv[1]), load(sys.argv[2])
KIND = {'unit': 'Unit', 'proj': 'Projectile', 'prop': 'Prop', 'mesh': 'Mesh'}
SKIP = re.compile(r'\.(BlueprintOrdinal|IconName|AlbedoName|NormalsName|SpecularName|MeshName|LookupName|SecondaryName|'
                  r'InertiaTensor.|SkirtSize.|SkirtOffset.|CommandCaps|ToggleCaps|BuildOnLayerCaps|ProjectileId|Description)$|'
                  r'\.Audio\.|\.Footprint\.|\.AltFootprint\.|^[a-z]+\.Mod\.')
out, unsure = [], []
for p, (n_o, nd_o, h_o) in sorted(orig.items()):
    kind = KIND.get(p.split('.')[0])
    if not kind: continue
    n_r, nd_r, h_r = raw.get(p, (0, 0, {}))
    if n_o <= n_r: continue
    added = {v: c - h_r.get(v, 0) for v, c in h_o.items() if c - h_r.get(v, 0) > 0}
    if not added or SKIP.search(p): continue
    path = p.split('.', 1)[1]
    v, c = max(added.items(), key=lambda kv: kv[1])
    if c < (n_o - n_r) * 0.9 or v in ('userdata', 'table') or v.endswith('...'):
        unsure.append(f'// unsure {kind} {path}: added {n_o - n_r}, {added}')
        continue
    if v in ('true', 'false'): val = f'B({v})'
    elif v.startswith('"'): val = f'S({v})'
    elif v in ('1.#INF', 'inf'): val = 'N(HUGE_VAL)'
    else: val = f'N({v})'
    out.append(f'{{BpKind::{kind}, "{path.replace(".[]", ".[]")}", {val}}},')
print('// Generated by tools/gen_bp_defaults.py from oracle probe histograms (bpstat): fields the')
print('// original engine adds to sim blueprints when the script table lacks them. {kind, path, value}')
print('\n'.join(out))
print('\n'.join(unsure))
