"""Generate src/sim/binding_names.inc: the names of the original engine's sim Lua bindings
(name + class only; the reference table engine-ref/bindings.json is private and not shipped).
usage: gen_binding_names.py engine-ref/bindings.json > src/sim/binding_names.inc"""
import json, sys
b = json.load(open(sys.argv[1]))
SETS = {'0xf5a124': 'sim', '0xf59680': 'core'}
rows = sorted({(SETS[x['head']], x['state'], x['name']) for x in b if x['head'] in SETS})
print('// Generated by tools/gen_binding_names.py: {set, C++ class ("" = global), name}')
for s, cls, name in rows:
    if s == 'core' and cls == '<global>': continue  # core globals live in script/core_bindings.cpp
    print(f'{{"{s}", "{"" if cls == "<global>" else cls}", "{name}"}},')
